'use strict';

/**
 * Render a store-backed CRUD handler for a single operation.
 * @param {{
 *   resource: string,
 *   op: 'list'|'detail'|'create'|'update'|'delete',
 *   stubId: string,
 * }} opts
 * @returns {string}
 */
function renderStoreHandler(opts) {
  const resource = String(opts.resource || 'items').replace(/[^a-zA-Z0-9_-]/g, '_');
  const op = opts.op;
  const stubId = opts.stubId || '';
  const colLit = JSON.stringify(resource);
  const emptyData = op === 'list' ? '[]' : 'null';

  const bodies = {
    list: `
  const rows = store.collectionList(${colLit});
  return { response: { code: 0, data: rows, message: '' }, httpStatus: 200 };`,
    detail: `
  const pathParts = String(reqPath || '').split('/').filter(Boolean);
  const id = (query && (query.id || query[${colLit} + 'Id'])) || pathParts[pathParts.length - 1];
  const row = store.collectionGet(${colLit}, String(id || ''));
  if (!row) {
    return { response: { code: 0, data: { id: String(id || '1') }, message: '' }, httpStatus: 200 };
  }
  return { response: { code: 0, data: row, message: '' }, httpStatus: 200 };`,
    create: `
  const payload = body && typeof body === 'object' ? body : {};
  const newId = String(payload.id != null ? payload.id : Date.now());
  const row = store.collectionPut(${colLit}, newId, payload);
  return { response: { code: 0, data: row, message: '' }, httpStatus: 200 };`,
    update: `
  const pathParts = String(reqPath || '').split('/').filter(Boolean);
  const id = (query && (query.id || query[${colLit} + 'Id'])) || pathParts[pathParts.length - 1];
  const existing = store.collectionGet(${colLit}, String(id || ''));
  const payload = body && typeof body === 'object' ? body : {};
  const base = existing || { id: String(id || '') };
  const row = store.collectionPut(${colLit}, String(id), Object.assign({}, base, payload, { id: String(id) }));
  return { response: { code: 0, data: row, message: '' }, httpStatus: 200 };`,
    delete: `
  const pathParts = String(reqPath || '').split('/').filter(Boolean);
  const id = (query && (query.id || query[${colLit} + 'Id'])) || pathParts[pathParts.length - 1];
  store.collectionDelete(${colLit}, String(id || ''));
  return { response: { code: 0, data: true, message: '' }, httpStatus: 200 };`,
  };

  const body = bodies[op] || bodies.list;

  return `/** Auto-generated by mox — store-backed ${op} — ${stubId}
 * mox:store resource=${resource}
 */
module.exports = ({ method, query, params, body, headers, caseId, store, path: reqPath }) => {
  const cases = {
    empty: { response: { code: 0, data: ${emptyData}, message: '' }, httpStatus: 200 },
    biz_error: { response: { code: 50000, data: null, message: 'mock business error' }, httpStatus: 200 },
    http_401: { response: { code: 401, data: null, message: 'unauthorized' }, httpStatus: 401 },
    http_403: { response: { code: 403, data: null, message: 'forbidden' }, httpStatus: 403 },
    http_404: { response: { code: 404, data: null, message: 'not found' }, httpStatus: 404 },
    http_500: { response: { code: 500, data: null, message: 'internal server error' }, httpStatus: 500 },
    http_502: { response: { code: 502, data: null, message: 'bad gateway / dep fail' }, httpStatus: 502 },
    dep_fail: { response: { code: 502, data: null, message: 'dependency failure' }, httpStatus: 502 },
    slow: { response: { code: 0, data: ${emptyData === '[]' ? '[]' : '{ id: "1" }'}, message: '' }, httpStatus: 200, delayMs: 3000 },
  };
  const idHeader = caseId || (headers && (headers['x-mock-case'] || headers['X-Mock-Case']));
  if (idHeader && idHeader !== 'success' && cases[idHeader]) return cases[idHeader];
${body}
};
`;
}

module.exports = { renderStoreHandler };
