'use strict';

/**
 * Export contract cases as MSW handlers for in-process unit tests.
 * Usage: mox export-msw [--out=./msw-handlers.js]
 */

const fs = require('fs');
const path = require('path');
const {
  resolveProjectSlug,
  projectDataDir,
  ensureProjectDirs,
} = require('../lib/paths');
const { loadContractsForCatalog } = require('../lib/catalog-merge');
const { appendAudit } = require('../lib/audit');

function contractToMswHandler(contract) {
  const method = (Array.isArray(contract.method)
    ? contract.method[0]
    : contract.method || 'GET'
  ).toLowerCase();
  const host = contract.host === '_default' ? '*' : contract.host;
  const url = `https://${host}${contract.path}`;
  const cases = contract.cases || [];
  const success = cases.find((c) => c.id === 'success') || cases[0];
  const body = success?.response || { code: 0, data: null, message: '' };
  const status = success?.httpStatus || 200;
  return `
  http.${method}('${url}', ({ request }) => {
    const caseId = request.headers.get('x-mock-case') || 'success';
    const cases = ${JSON.stringify(
      Object.fromEntries(
        cases.map((c) => [
          c.id,
          { status: c.httpStatus || 200, body: c.response || null },
        ]),
      ),
      null,
      2,
    )};
    const entry = cases[caseId] || cases.success || { status: ${status}, body: ${JSON.stringify(body)} };
    return HttpResponse.json(entry.body, { status: entry.status });
  })`;
}

function exportMsw(opts = {}) {
  const projectDir = opts.projectDir || process.cwd();
  const projectSlug = resolveProjectSlug(projectDir, opts.name);
  ensureProjectDirs(projectSlug);
  const contracts = loadContractsForCatalog(projectSlug);
  if (!contracts.length) {
    throw new Error('no contracts — run mox init or import-openapi first');
  }

  const handlers = [];
  for (const contract of contracts) {
    handlers.push(contractToMswHandler(contract));
  }

  const out =
    opts.out ||
    path.join(projectDataDir(projectSlug), 'exports', 'msw-handlers.js');
  fs.mkdirSync(path.dirname(out), { recursive: true });
  const src = `/* auto-generated by mox export-msw — do not edit */
import { http, HttpResponse } from 'msw';

export const handlers = [
${handlers.join(',\n')}
];
`;
  fs.writeFileSync(out, src);
  appendAudit(projectSlug, {
    command: 'export-msw',
    taskId: opts.taskId || null,
    summary: `handlers=${handlers.length} out=${out}`,
  });
  console.log(`[mox] export-msw wrote ${out} (${handlers.length} handlers)`);
  return { out, count: handlers.length };
}

module.exports = { exportMsw, contractToMswHandler };

if (require.main === module) {
  exportMsw({ projectDir: process.cwd() });
}
